### ISSUE TITLE
ошибка при загрузке light

### ISSUE THREAD

**Issue by andvikt** [andvikt/mega_hacs#101]
**Описание**
Ошибка при загрузке light

**Версии систем**
Enviroment: raspberry/linux/windows/macos/docker
HA version: 
mega_hacs version:
megad firmware version:
используется mqtt: true/false

**Ожидаемое поведение**
Описание правильного поведения

**Screenshots**

**LOG**
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/mega/light.py", line 94, in async_setup_entry
    light = MegaLight(mega=hub, port=port, config_entry=config_entry, **data)
  File "/config/custom_components/mega/entities.py", line 285, in __init__
    super().__init__(
  File "/config/custom_components/mega/entities.py", line 216, in __init__
    self.mega.subscribe(self.port, callback=self.__update)
  File "/config/custom_components/mega/hub.py", line 430, in subscribe
    f'subscribe %s %s', port, str(callback)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 888, in __repr__
    return f"<Entity {self.name}: {self.state}>"
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 935, in state
    return STATE_ON if self.is_on else STATE_OFF
  File "/config/custom_components/mega/entities.py", line 356, in is_on
    if self.dimmer:
AttributeError: 'MegaLight' object has no attribute 'dimmer'[/code]
```

**Comment by andvikt** [comment]
исправлено в 1.1.8b7
