### ISSUE TITLE
Проблемы при добавление mega-2561 после обновления HA

### ISSUE THREAD

**Issue by lesovoy-alim** [andvikt/mega_hacs#155]
**Описание**
После обновления на Home Assistant 2023.10.1 не добавляется мега через интеграцию.
Выполнены действия:
- Обновлена интеграция до последней версии
- Снес и переустановил HACS
- Выполнил полностью новую установку HA OS, проблема повторяется

**Версии систем**
Enviroment: linux
HA version: Home Assistant 2023.10.1
mega_hacs version: v1.1.6
megad firmware version: MegaD-2561 by [ab-log.ru](http://ab-log.ru/) (fw: 4.60b6)
используется mqtt: false

**Ожидаемое поведение**
Описание правильного поведения

**Screenshots**
<img width="565" alt="image" src="https://github.com/andvikt/mega_hacs/assets/52373895/cff02e3d-0182-432b-8ec5-0409a94f4646">
**LOG**
2023-10-07 16:55:45.115 ERROR (MainThread) [frontend.js.latest.202310050] Uncaught error from Safari 16.5 on Mac OS 10.15.7
Script error.
null
@:0:0
2023-10-07 16:55:47.953 ERROR (MainThread) [custom_components.mega.config_flow.mega] while setting allowed hosts
Traceback (most recent call last):
  File "/config/custom_components/mega/hub.py", line 164, in __init__
    hass.data[DOMAIN][CONF_HTTP].protected = protected
    ~~~~~~~~~^^^^^^^^
KeyError: 'mega'
2023-10-07 16:55:48.235 ERROR (MainThread) [custom_components.mega.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/mega/config_flow.py", line 82, in async_step_user
    config = await hub.get_config(nports=user_input.get(CONF_NPORTS, 37))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mega/hub.py", line 511, in get_config
    async for port, cfg in self.scan_ports(nports):
  File "/config/custom_components/mega/hub.py", line 456, in scan_ports
    ret = await self.scan_port(x)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mega/hub.py", line 451, in scan_port
    data = await self.request(pt=port)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mega/hub.py", line 308, in request
    ret = await req.text()
          ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1086, in text
    return self._body.decode(  # type: ignore[no-any-return,union-attr]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 684: invalid continuation byte

**Comment by lesovoy-alim** [comment]
Помогло замена кодировки в hub.py 308 строка
`ret = await res.text("iso-8859-5")`

**Comment by andvikt** [comment]
исправлено в v1.1.7
