### ISSUE TITLE
Не отображаются актуальные данные датчиков i2c

### ISSUE THREAD

**Issue by wji9na** [andvikt/mega_hacs#168]
**Описание**
После обновления HomeAssistant перестали отображаться актуальные данные датчиков i2c, данные судя по дебагу поступают от датчиков, но не отображаются в карточке и состоянии датчика. Эта проблема появилась достаточно давно, поэтому я тянул с обновлением, но больше откладывать не мог. На скриншоте видно частоту обновления информации до обновления HA и после. При этом один датчик продолжает обновляться как ни в чём ни бывало.

**Версии систем**
Enviroment: homeassistantos/proxmoxve
HA version: 11.3
mega_hacs version: 1.1.7
megad firmware version: 4.51b2
используется mqtt: false

**Ожидаемое поведение**
Обновление данных датчика каждые 30 секунд, в соответствии с настройками обновления входов интеграции.

**Screenshots**
не отображающийся корректно датчик
![image](https://github.com/andvikt/mega_hacs/assets/5336656/64332bd1-6e6f-42a9-97f8-a783a2580919)
единственный отображающийся датчик
![image](https://github.com/andvikt/mega_hacs/assets/5336656/3222bc8e-dee4-4d29-8880-fdcd91caa869)

**LOG**
пример получения данных от датчика, значения которого не обновляются корректно, после обновления:
```
2024-01-10 10:09:11.291 DEBUG (MainThread) [custom_components.mega.mega] request: http://192.168.1.1/sec/?pt=43&scl=30&i2c_dev=htu21d&i2c_par=1
2024-01-10 10:09:11.351 DEBUG (MainThread) [custom_components.mega.mega] response -7.96
2024-01-10 10:09:11.351 DEBUG (MainThread) [custom_components.mega.mega] i2c response: {(('pt', '43'), ('scl', '30'), ('i2c_dev', 'htu21d'), ('i2c_par', 1)): '-7.96'}
```
в конце процедуры обновления входов от меги в логе присутствует ошибка:
```
2024-01-10 10:09:11.446 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 639, in state
    numerical_value = int(value)
                      ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'NA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 642, in state
    numerical_value = float(value)
                      ^^^^^^^^^^^^
ValueError: could not convert string to float: 'NA'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 947, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 646, in state
    raise ValueError(
ValueError: Sensor sensor.mega_31_htu21d_temperature has device class 'temperature', state class 'None' unit '°C' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: 'NA' (<class 'str'>)
```

**Comment by wji9na** [comment]
обновил интеграцию на бета версию v1.1.8b12 заработало отображение всех датчиков кроме одного, температурного, на 31 входе меги подключен комбинированный датчик температуры/влажности/освещенности по i2c, а именно HTU21D и сенсор освещённости MAX44009, [(датчик вот такой, как и остальные)](https://www.ab-log.ru/forum/viewtopic.php?f=1&t=1624) показания влажности и освещенности приходят и отображаются исправно, а показания температурного фиксируются с некоторой периодичностью, но отображаются как неизвестные
![image](https://github.com/andvikt/mega_hacs/assets/5336656/f9189b2f-689f-4de0-8c8a-76b9af97d9f2)
в логах сообщения о том, что датчик не возвращает значение
```
2024-01-10 11:22:11.004 DEBUG (MainThread) [custom_components.mega.mega] request: http://192.168.1.1/sec/?pt=31&scl=30&i2c_dev=htu21d&i2c_par=1
2024-01-10 11:22:11.015 DEBUG (MainThread) [custom_components.mega.mega] response NA
2024-01-10 11:22:11.015 DEBUG (MainThread) [custom_components.mega.mega] i2c response: {(('pt', '31'), ('scl', '30'), ('i2c_dev', 'htu21d'), ('i2c_par', 1)): None}
```
однако тот же запрос в браузере возвращает данные
![image](https://github.com/andvikt/mega_hacs/assets/5336656/53837f65-0b09-403c-b283-a72f87d4d82e)
