### ISSUE TITLE
Unknown error occurred при нажатии обновтить

### ISSUE THREAD

**Issue by Sandteufel** [andvikt/mega_hacs#176]
Добавил датчики и решил обновить и тут вот такое: Unknown error occurred

2024.10.4
Enviroment: docker
HA version:  2024.10.4
mega_hacs version: v1.1.7
megad firmware version: 4.64b8
используется mqtt: false

Обновление датчиков.

2024-11-06 20:25:41.183 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 285, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 370, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 417, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mega/config_flow.py", line 124, in async_step_init
    self.config_entry.data = cfg
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 443, in __setattr__
    raise AttributeError(
AttributeError: data cannot be changed directly, use async_update_entry instead
2024-11-06 20:26:18.581 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.mega.light.MegaLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/andvikt/mega_hacs/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-11-06 20:26:18.582 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.mega.light.MegaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/andvikt/mega_hacs/issues
2024-11-06 20:26:18.582 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.mega.light.MegaLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/andvikt/mega_hacs/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-11-06 20:26:18.582 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.mega.light.MegaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/andvikt/mega_hacs/issues
2024-11-06 20:26:18.583 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.mega.light.MegaLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/andvikt/mega_hacs/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-11-06 20:26:18.583 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.mega.light.MegaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/andvikt/mega_hacs/issues
2024-11-06 20:26:18.583 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.mega.light.MegaLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/andvikt/mega_hacs/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-11-06 20:26:18.583 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.mega.light.MegaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/andvikt/mega_hacs/issues
2024-11-06 20:26:18.584 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.mega.light.MegaLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/andvikt/mega_hacs/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-11-06 20:26:18.584 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.mega.light.MegaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/andvikt/mega_hacs/issues
2024-11-06 20:26:18.584 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.mega.light.MegaLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/andvikt/mega_hacs/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-11-06 20:26:18.584 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.mega.light.MegaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/andvikt/mega_hacs/issues
2024-11-06 20:26:18.588 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.mega.light.MegaLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/andvikt/mega_hacs/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-11-06 20:26:18.589 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.mega.light.MegaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/andvikt/mega_hacs/issues
2024-11-06 20:26:18.589 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.mega.light.MegaLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/andvikt/mega_hacs/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-11-06 20:26:18.589 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.mega.light.MegaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/andvikt/mega_hacs/issues
2024-11-06 20:26:18.589 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.mega.light.MegaLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/andvikt/mega_hacs/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-11-06 20:26:18.590 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.mega.light.MegaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/andvikt/mega_hacs/issues
2024-11-06 20:26:18.590 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.mega.light.MegaLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/andvikt/mega_hacs/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-11-06 20:26:18.590 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.mega.light.MegaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/andvikt/mega_hacs/issues
2024-11-06 20:26:18.590 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.mega.light.MegaLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/andvikt/mega_hacs/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-11-06 20:26:18.590 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.mega.light.MegaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/andvikt/mega_hacs/issues
2024-11-06 20:26:18.591 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.mega.light.MegaLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/andvikt/mega_hacs/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-11-06 20:26:18.591 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.mega.light.MegaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/andvikt/mega_hacs/issues
2024-11-06 20:26:18.591 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.mega.light.MegaLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/andvikt/mega_hacs/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-11-06 20:26:18.591 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.mega.light.MegaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/andvikt/mega_hacs/issues
2024-11-06 20:26:18.592 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.mega.light.MegaLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color modes, please create a bug report at https://github.com/andvikt/mega_hacs/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-11-06 20:26:18.592 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.mega.light.MegaLight'>) does not set supported color modes, this will stop working in Home Assistant Core 2025.3, please create a bug report at https://github.com/andvikt/mega_hacs/issues

**Comment by avkosin** [comment]
Точно такая же проблема
