### ISSUE TITLE
бета версия с поддержкой расширителей

### ISSUE THREAD

**Issue by xtiitx** [andvikt/mega_hacs#23]
**Описание**
После обновления на бету перестали работать выходы, Расширитель не определился

**Версии систем**
Enviroment: linux
HA version: 2021.2.3
mega_hacs version: v0.5.1b2
megad firmware version: fw: 4.44b9
используется mqtt: false

**LOG**

```
2021-02-26 15:43:33 ERROR (MainThread) [homeassistant.components.light] Error while setting up mega platform for light
Traceback (most recent call last):
  File "/home/admini/HA/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/home/admini/.homeassistant/custom_components/mega/light.py", line 64, in async_setup_entry
    port = int(port)
ValueError: invalid literal for int() with base 10: '8e0'
2021-02-26 15:43:33 ERROR (MainThread) [homeassistant.components.switch] Error while setting up mega platform for switch
Traceback (most recent call last):
  File "/home/admini/HA/lib/python3.8/site-packages/homeassistant/helpers/entity_platform.py", line 198, in _async_setup_platform
    await asyncio.shield(task)
  File "/home/admini/.homeassistant/custom_components/mega/switch.py", line 53, in async_setup_entry
    port = int(port)
ValueError: invalid literal for int() with base 10: '8e0'

```

**Comment by andvikt** [comment]
Спасибо, поправлю

**Comment by andvikt** [comment]
Ну так у вас совсем не новая версия ) обновитесь до последней беты.
