### ISSUE TITLE
Нет соединения

### ISSUE THREAD

**Issue by scherb-e** [andvikt/mega_hacs#28]
После перезагрузки Меги в интеграции связь с контроллером не восстанавливается

Logger: homeassistant.config_entries
Source: custom_components/mega/hub.py:265
First occurred: 17:54:04 (1 occurrences)
Last logged: 17:54:04

Error setting up entry mega for mega
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 975, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1025, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 1010, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 924, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 496, in sock_connect
    return await fut
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 528, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
OSError: [Errno 113] Connect call failed ('192.168.16.14', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/mega/__init__.py", line 150, in async_setup_entry
    hub: MegaD = await _add_mega(hass, entry)
  File "/config/custom_components/mega/__init__.py", line 138, in _add_mega
    hub = await get_hub(hass, entry)
  File "/config/custom_components/mega/__init__.py", line 132, in get_hub
    hub.mqtt_id = await hub.get_mqtt_id()
  File "/config/custom_components/mega/hub.py", line 265, in get_mqtt_id
    async with aiohttp.request(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 1168, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client.py", line 527, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 541, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 898, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1057, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 1026, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.8/site-packages/aiohttp/connector.py", line 981, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.16.14:80 ssl:default [Connect call failed ('192.168.16.14', 80)]

**Comment by andvikt** [comment]
Это конечно очень странно, но вообще это мега не отвечает. Вы уверены что контроллер доступен в сети по этому адресу?

Я сделаю обработку этой ошибки и попробую зациклить ожидание доступности.

**Comment by scherb-e** [comment]
Мега доступна, да. Если перезагрузить ХА - он уже запускается соединенным с мегой. Но до тех пор соединение отсутствует.

**Comment by andvikt** [comment]
Это весь лог? Просто то что вы прислали-это ошибка возникающая в процессе инициализации, те при старте ha. Почему у вас при перезагрузке меги рестартится ha?

**Comment by andvikt** [comment]
Я вижу ситуацию так: у вас совпал момент перезагрузки ha и меги, в этот момент мега была недоступна, возникла такая ошибка и все сломалось, тк в момент инициализации запрашиваются кое-какие параметры с меги

**Comment by scherb-e** [comment]
Похоже вы правы  - это частный случай учитывая, что мега быстрее ХА стартует и на момент того лога у меня так совпало.
Попробовал несколько сценариев развития:

1. ХА запущен, перезагрузка меги - работает
2. Мега запущена, перезагрузка ХА - работает
3. Мега выключена, перезагрузка ХА и включение меги - связи нет.

т.е. если при запуске ХА мега была недоступна, то дальше связь с мегой не восстанавливается.
