### ISSUE TITLE
MegaD перестает работать после перезагрузки HA

### ISSUE THREAD

**Issue by Foroxon** [andvikt/mega_hacs#65]
**Описание**
После перехода на новый комутатор Cisco (CBS110-24PP-EU) обнаружилась проблема с интеграцией.
После перезагрузки HA некоторые меги (у меня их 3) перестают работать (скриншот ниже).
Меги отваливаются абсолютно случайным образом при каждой перезагрузке HA. Иногда приходится по 5-6 раз перезагружать HA чтобы все 3 меги подтянулись в интеграции и это жутко неудобно. При этом меги всегда доступны по локальному адресу.
Если я правильно прочел логи, то проблема в таймауте при попытке связаться с мегой при старте интеграции. Возможно ли увеличить таймаут с 5 сек. до 10 (или даже больше).
Я понимаю, что это особености взаимодействия MegaD и маршрутизатора Cisco, но возможно проблему удастся решить увеличением таймаута.

**Версии систем**
Enviroment: raspberry
HA version: core-2021.10.3
mega_hacs version: v1.0.9
megad firmware version: 4.53b1
используется mqtt: false

**Ожидаемое поведение**
Мега не отваливается в HA после перезагрузки

**Screenshots**
<img width="273" alt="Screen Shot 2021-10-11 at 13 38 30" src="https://user-images.githubusercontent.com/925166/136777949-672e6183-451a-4976-b946-1bc1047645c0.png">
<img width="274" alt="Screen Shot 2021-10-11 at 13 38 43" src="https://user-images.githubusercontent.com/925166/136777951-06be981b-9178-46eb-b110-75b245001399.png">

**LOG**
```
Logger: homeassistant.config_entries
Source: custom_components/mega/hub.py:302
Integration: mega (documentation, issues)
First occurred: 13:15:39 (2 occurrences)
Last logged: 13:15:39

Error setting up entry lig2 for mega
Error setting up entry lig1 for mega
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/mega/__init__.py", line 180, in async_setup_entry
    hub: MegaD = await _add_mega(hass, entry)
  File "/config/custom_components/mega/__init__.py", line 169, in _add_mega
    hub.fw = await hub.get_fw()
  File "/config/custom_components/mega/hub.py", line 287, in get_fw
    data = await self.request()
  File "/config/custom_components/mega/hub.py", line 302, in request
    async with aiohttp.request("get", url=url, timeout=aiohttp.ClientTimeout(total=5)) as req:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1161, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 544, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 905, in start
    self._continue = None
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

**Comment by andvikt** [comment]
Еще мне подсказывает коллега ) была тоже на циске проблема, в сети много разных устройств и некоторые шлют постоянно широковещательные пакеты, это убивает сеть меги, тк она вынуждена отфильтрорывать ненужные пакеты и ввиду слабого процессора делает это медленно и полезные пакеты до нее просто не доходят. Решение-перевести меги в выделенный vlan
