### ISSUE TITLE
Error during setup of component mega

### ISSUE THREAD

**Issue by avdeevsv91** [andvikt/mega_hacs#9]
**Описание**
После обновления до версии 0.3.17 компонент перестал стартовать

**Версии систем**
Enviroment: raspberry
HA version: 2021.2.2
mega_hacs version: 0.3.17
используется mqtt: true

**LOG**
```yaml
Logger: homeassistant.setup
Source: custom_components/mega/http.py:31
First occurred: 13:38:04 (1 occurrences)
Last logged: 13:38:04

Error during setup of component mega
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component
    result = await task
  File "/config/custom_components/mega/__init__.py", line 68, in async_setup
    hass.data[DOMAIN][CONF_HTTP] = view = MegaView(cfg=config.get(DOMAIN, {}))
  File "/config/custom_components/mega/http.py", line 30, in __init__
    self.templates: typing.Dict[str, typing.Dict[str, Template]] = {
  File "/config/custom_components/mega/http.py", line 31, in <dictcomp>
    mid: {
TypeError: 'bool' object is not iterable
```

**Comment by andvikt** [comment]
исправил )
